// Code generated by protoc-gen-go. DO NOT EDIT.
// source: binlogdata.proto

package binlogdata // import "vitess.io/vitess/go/vt/proto/binlogdata"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import query "vitess.io/vitess/go/vt/proto/query"
import topodata "vitess.io/vitess/go/vt/proto/topodata"
import vschema "vitess.io/vitess/go/vt/proto/vschema"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BinlogTransaction_Statement_Category int32

const (
	BinlogTransaction_Statement_BL_UNRECOGNIZED BinlogTransaction_Statement_Category = 0
	BinlogTransaction_Statement_BL_BEGIN        BinlogTransaction_Statement_Category = 1
	BinlogTransaction_Statement_BL_COMMIT       BinlogTransaction_Statement_Category = 2
	BinlogTransaction_Statement_BL_ROLLBACK     BinlogTransaction_Statement_Category = 3
	// BL_DML is deprecated.
	BinlogTransaction_Statement_BL_DML_DEPRECATED BinlogTransaction_Statement_Category = 4
	BinlogTransaction_Statement_BL_DDL            BinlogTransaction_Statement_Category = 5
	BinlogTransaction_Statement_BL_SET            BinlogTransaction_Statement_Category = 6
	BinlogTransaction_Statement_BL_INSERT         BinlogTransaction_Statement_Category = 7
	BinlogTransaction_Statement_BL_UPDATE         BinlogTransaction_Statement_Category = 8
	BinlogTransaction_Statement_BL_DELETE         BinlogTransaction_Statement_Category = 9
)

var BinlogTransaction_Statement_Category_name = map[int32]string{
	0: "BL_UNRECOGNIZED",
	1: "BL_BEGIN",
	2: "BL_COMMIT",
	3: "BL_ROLLBACK",
	4: "BL_DML_DEPRECATED",
	5: "BL_DDL",
	6: "BL_SET",
	7: "BL_INSERT",
	8: "BL_UPDATE",
	9: "BL_DELETE",
}
var BinlogTransaction_Statement_Category_value = map[string]int32{
	"BL_UNRECOGNIZED":   0,
	"BL_BEGIN":          1,
	"BL_COMMIT":         2,
	"BL_ROLLBACK":       3,
	"BL_DML_DEPRECATED": 4,
	"BL_DDL":            5,
	"BL_SET":            6,
	"BL_INSERT":         7,
	"BL_UPDATE":         8,
	"BL_DELETE":         9,
}

func (x BinlogTransaction_Statement_Category) String() string {
	return proto.EnumName(BinlogTransaction_Statement_Category_name, int32(x))
}
func (BinlogTransaction_Statement_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{1, 0, 0}
}

// Charset is the per-statement charset info from a QUERY_EVENT binlog entry.
type Charset struct {
	// @@session.character_set_client
	Client int32 `protobuf:"varint,1,opt,name=client" json:"client,omitempty"`
	// @@session.collation_connection
	Conn int32 `protobuf:"varint,2,opt,name=conn" json:"conn,omitempty"`
	// @@session.collation_server
	Server               int32    `protobuf:"varint,3,opt,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Charset) Reset()         { *m = Charset{} }
func (m *Charset) String() string { return proto.CompactTextString(m) }
func (*Charset) ProtoMessage()    {}
func (*Charset) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{0}
}
func (m *Charset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Charset.Unmarshal(m, b)
}
func (m *Charset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Charset.Marshal(b, m, deterministic)
}
func (dst *Charset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charset.Merge(dst, src)
}
func (m *Charset) XXX_Size() int {
	return xxx_messageInfo_Charset.Size(m)
}
func (m *Charset) XXX_DiscardUnknown() {
	xxx_messageInfo_Charset.DiscardUnknown(m)
}

var xxx_messageInfo_Charset proto.InternalMessageInfo

func (m *Charset) GetClient() int32 {
	if m != nil {
		return m.Client
	}
	return 0
}

func (m *Charset) GetConn() int32 {
	if m != nil {
		return m.Conn
	}
	return 0
}

func (m *Charset) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

// BinlogTransaction describes a transaction inside the binlogs.
// It is streamed by vttablet for filtered replication, used during resharding.
type BinlogTransaction struct {
	// the statements in this transaction
	Statements []*BinlogTransaction_Statement `protobuf:"bytes,1,rep,name=statements" json:"statements,omitempty"`
	// The Event Token for this event.
	EventToken           *query.EventToken `protobuf:"bytes,4,opt,name=event_token,json=eventToken" json:"event_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BinlogTransaction) Reset()         { *m = BinlogTransaction{} }
func (m *BinlogTransaction) String() string { return proto.CompactTextString(m) }
func (*BinlogTransaction) ProtoMessage()    {}
func (*BinlogTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{1}
}
func (m *BinlogTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogTransaction.Unmarshal(m, b)
}
func (m *BinlogTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogTransaction.Marshal(b, m, deterministic)
}
func (dst *BinlogTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogTransaction.Merge(dst, src)
}
func (m *BinlogTransaction) XXX_Size() int {
	return xxx_messageInfo_BinlogTransaction.Size(m)
}
func (m *BinlogTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogTransaction proto.InternalMessageInfo

func (m *BinlogTransaction) GetStatements() []*BinlogTransaction_Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *BinlogTransaction) GetEventToken() *query.EventToken {
	if m != nil {
		return m.EventToken
	}
	return nil
}

type BinlogTransaction_Statement struct {
	// what type of statement is this?
	Category BinlogTransaction_Statement_Category `protobuf:"varint,1,opt,name=category,enum=binlogdata.BinlogTransaction_Statement_Category" json:"category,omitempty"`
	// charset of this statement, if different from pre-negotiated default.
	Charset *Charset `protobuf:"bytes,2,opt,name=charset" json:"charset,omitempty"`
	// the sql
	Sql                  []byte   `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinlogTransaction_Statement) Reset()         { *m = BinlogTransaction_Statement{} }
func (m *BinlogTransaction_Statement) String() string { return proto.CompactTextString(m) }
func (*BinlogTransaction_Statement) ProtoMessage()    {}
func (*BinlogTransaction_Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{1, 0}
}
func (m *BinlogTransaction_Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogTransaction_Statement.Unmarshal(m, b)
}
func (m *BinlogTransaction_Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogTransaction_Statement.Marshal(b, m, deterministic)
}
func (dst *BinlogTransaction_Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogTransaction_Statement.Merge(dst, src)
}
func (m *BinlogTransaction_Statement) XXX_Size() int {
	return xxx_messageInfo_BinlogTransaction_Statement.Size(m)
}
func (m *BinlogTransaction_Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogTransaction_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogTransaction_Statement proto.InternalMessageInfo

func (m *BinlogTransaction_Statement) GetCategory() BinlogTransaction_Statement_Category {
	if m != nil {
		return m.Category
	}
	return BinlogTransaction_Statement_BL_UNRECOGNIZED
}

func (m *BinlogTransaction_Statement) GetCharset() *Charset {
	if m != nil {
		return m.Charset
	}
	return nil
}

func (m *BinlogTransaction_Statement) GetSql() []byte {
	if m != nil {
		return m.Sql
	}
	return nil
}

// StreamFilterRequest is the payload to StreamFilter
type StreamFilterRequest struct {
	// where to start
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	// what to get
	Filter *Filter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	// default charset on the player side
	Charset              *Charset `protobuf:"bytes,3,opt,name=charset" json:"charset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamFilterRequest) Reset()         { *m = StreamFilterRequest{} }
func (m *StreamFilterRequest) String() string { return proto.CompactTextString(m) }
func (*StreamFilterRequest) ProtoMessage()    {}
func (*StreamFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{2}
}
func (m *StreamFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamFilterRequest.Unmarshal(m, b)
}
func (m *StreamFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamFilterRequest.Marshal(b, m, deterministic)
}
func (dst *StreamFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamFilterRequest.Merge(dst, src)
}
func (m *StreamFilterRequest) XXX_Size() int {
	return xxx_messageInfo_StreamFilterRequest.Size(m)
}
func (m *StreamFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamFilterRequest proto.InternalMessageInfo

func (m *StreamFilterRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *StreamFilterRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *StreamFilterRequest) GetCharset() *Charset {
	if m != nil {
		return m.Charset
	}
	return nil
}

// StreamFilterResponse is the response from StreamFilter
type StreamFilterResponse struct {
	BinlogTransaction    *BinlogTransaction `protobuf:"bytes,1,opt,name=binlog_transaction,json=binlogTransaction" json:"binlog_transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamFilterResponse) Reset()         { *m = StreamFilterResponse{} }
func (m *StreamFilterResponse) String() string { return proto.CompactTextString(m) }
func (*StreamFilterResponse) ProtoMessage()    {}
func (*StreamFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{3}
}
func (m *StreamFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamFilterResponse.Unmarshal(m, b)
}
func (m *StreamFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamFilterResponse.Marshal(b, m, deterministic)
}
func (dst *StreamFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamFilterResponse.Merge(dst, src)
}
func (m *StreamFilterResponse) XXX_Size() int {
	return xxx_messageInfo_StreamFilterResponse.Size(m)
}
func (m *StreamFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamFilterResponse proto.InternalMessageInfo

func (m *StreamFilterResponse) GetBinlogTransaction() *BinlogTransaction {
	if m != nil {
		return m.BinlogTransaction
	}
	return nil
}

// StreamKeyRangeRequest is the payload to StreamKeyRange
type StreamKeyRangeRequest struct {
	// where to start
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	// what to get
	KeyRange *topodata.KeyRange `protobuf:"bytes,2,opt,name=key_range,json=keyRange" json:"key_range,omitempty"`
	// default charset on the player side
	Charset              *Charset `protobuf:"bytes,3,opt,name=charset" json:"charset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamKeyRangeRequest) Reset()         { *m = StreamKeyRangeRequest{} }
func (m *StreamKeyRangeRequest) String() string { return proto.CompactTextString(m) }
func (*StreamKeyRangeRequest) ProtoMessage()    {}
func (*StreamKeyRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{4}
}
func (m *StreamKeyRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamKeyRangeRequest.Unmarshal(m, b)
}
func (m *StreamKeyRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamKeyRangeRequest.Marshal(b, m, deterministic)
}
func (dst *StreamKeyRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamKeyRangeRequest.Merge(dst, src)
}
func (m *StreamKeyRangeRequest) XXX_Size() int {
	return xxx_messageInfo_StreamKeyRangeRequest.Size(m)
}
func (m *StreamKeyRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamKeyRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamKeyRangeRequest proto.InternalMessageInfo

func (m *StreamKeyRangeRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *StreamKeyRangeRequest) GetKeyRange() *topodata.KeyRange {
	if m != nil {
		return m.KeyRange
	}
	return nil
}

func (m *StreamKeyRangeRequest) GetCharset() *Charset {
	if m != nil {
		return m.Charset
	}
	return nil
}

// StreamKeyRangeResponse is the response from StreamKeyRange
type StreamKeyRangeResponse struct {
	BinlogTransaction    *BinlogTransaction `protobuf:"bytes,1,opt,name=binlog_transaction,json=binlogTransaction" json:"binlog_transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamKeyRangeResponse) Reset()         { *m = StreamKeyRangeResponse{} }
func (m *StreamKeyRangeResponse) String() string { return proto.CompactTextString(m) }
func (*StreamKeyRangeResponse) ProtoMessage()    {}
func (*StreamKeyRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{5}
}
func (m *StreamKeyRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamKeyRangeResponse.Unmarshal(m, b)
}
func (m *StreamKeyRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamKeyRangeResponse.Marshal(b, m, deterministic)
}
func (dst *StreamKeyRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamKeyRangeResponse.Merge(dst, src)
}
func (m *StreamKeyRangeResponse) XXX_Size() int {
	return xxx_messageInfo_StreamKeyRangeResponse.Size(m)
}
func (m *StreamKeyRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamKeyRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamKeyRangeResponse proto.InternalMessageInfo

func (m *StreamKeyRangeResponse) GetBinlogTransaction() *BinlogTransaction {
	if m != nil {
		return m.BinlogTransaction
	}
	return nil
}

// StreamTablesRequest is the payload to StreamTables
type StreamTablesRequest struct {
	// where to start
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	// what to get
	Tables []string `protobuf:"bytes,2,rep,name=tables" json:"tables,omitempty"`
	// default charset on the player side
	Charset              *Charset `protobuf:"bytes,3,opt,name=charset" json:"charset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTablesRequest) Reset()         { *m = StreamTablesRequest{} }
func (m *StreamTablesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamTablesRequest) ProtoMessage()    {}
func (*StreamTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{6}
}
func (m *StreamTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTablesRequest.Unmarshal(m, b)
}
func (m *StreamTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTablesRequest.Marshal(b, m, deterministic)
}
func (dst *StreamTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTablesRequest.Merge(dst, src)
}
func (m *StreamTablesRequest) XXX_Size() int {
	return xxx_messageInfo_StreamTablesRequest.Size(m)
}
func (m *StreamTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTablesRequest proto.InternalMessageInfo

func (m *StreamTablesRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *StreamTablesRequest) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *StreamTablesRequest) GetCharset() *Charset {
	if m != nil {
		return m.Charset
	}
	return nil
}

// StreamTablesResponse is the response from StreamTables
type StreamTablesResponse struct {
	BinlogTransaction    *BinlogTransaction `protobuf:"bytes,1,opt,name=binlog_transaction,json=binlogTransaction" json:"binlog_transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamTablesResponse) Reset()         { *m = StreamTablesResponse{} }
func (m *StreamTablesResponse) String() string { return proto.CompactTextString(m) }
func (*StreamTablesResponse) ProtoMessage()    {}
func (*StreamTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{7}
}
func (m *StreamTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTablesResponse.Unmarshal(m, b)
}
func (m *StreamTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTablesResponse.Marshal(b, m, deterministic)
}
func (dst *StreamTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTablesResponse.Merge(dst, src)
}
func (m *StreamTablesResponse) XXX_Size() int {
	return xxx_messageInfo_StreamTablesResponse.Size(m)
}
func (m *StreamTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTablesResponse proto.InternalMessageInfo

func (m *StreamTablesResponse) GetBinlogTransaction() *BinlogTransaction {
	if m != nil {
		return m.BinlogTransaction
	}
	return nil
}

type Filter struct {
	Vschema              *vschema.Keyspace  `protobuf:"bytes,1,opt,name=vschema" json:"vschema,omitempty"`
	KeyRange             *topodata.KeyRange `protobuf:"bytes,2,opt,name=key_range,json=keyRange" json:"key_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{8}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetVschema() *vschema.Keyspace {
	if m != nil {
		return m.Vschema
	}
	return nil
}

func (m *Filter) GetKeyRange() *topodata.KeyRange {
	if m != nil {
		return m.KeyRange
	}
	return nil
}

// BinlogSource specifies the source  and filter parameters for
// Filtered Replication. It currently supports a keyrange
// or a list of tables.
type BinlogSource struct {
	// the source keyspace
	Keyspace string `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	// the source shard
	Shard string `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
	// the source tablet type
	TabletType topodata.TabletType `protobuf:"varint,3,opt,name=tablet_type,json=tabletType,enum=topodata.TabletType" json:"tablet_type,omitempty"`
	// key_range is set if the request is for a keyrange
	KeyRange *topodata.KeyRange `protobuf:"bytes,4,opt,name=key_range,json=keyRange" json:"key_range,omitempty"`
	// tables is set if the request is for a list of tables
	Tables               []string `protobuf:"bytes,5,rep,name=tables" json:"tables,omitempty"`
	Filter               *Filter  `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinlogSource) Reset()         { *m = BinlogSource{} }
func (m *BinlogSource) String() string { return proto.CompactTextString(m) }
func (*BinlogSource) ProtoMessage()    {}
func (*BinlogSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_binlogdata_ad0a67dfb182b939, []int{9}
}
func (m *BinlogSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinlogSource.Unmarshal(m, b)
}
func (m *BinlogSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinlogSource.Marshal(b, m, deterministic)
}
func (dst *BinlogSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinlogSource.Merge(dst, src)
}
func (m *BinlogSource) XXX_Size() int {
	return xxx_messageInfo_BinlogSource.Size(m)
}
func (m *BinlogSource) XXX_DiscardUnknown() {
	xxx_messageInfo_BinlogSource.DiscardUnknown(m)
}

var xxx_messageInfo_BinlogSource proto.InternalMessageInfo

func (m *BinlogSource) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *BinlogSource) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *BinlogSource) GetTabletType() topodata.TabletType {
	if m != nil {
		return m.TabletType
	}
	return topodata.TabletType_UNKNOWN
}

func (m *BinlogSource) GetKeyRange() *topodata.KeyRange {
	if m != nil {
		return m.KeyRange
	}
	return nil
}

func (m *BinlogSource) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *BinlogSource) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*Charset)(nil), "binlogdata.Charset")
	proto.RegisterType((*BinlogTransaction)(nil), "binlogdata.BinlogTransaction")
	proto.RegisterType((*BinlogTransaction_Statement)(nil), "binlogdata.BinlogTransaction.Statement")
	proto.RegisterType((*StreamFilterRequest)(nil), "binlogdata.StreamFilterRequest")
	proto.RegisterType((*StreamFilterResponse)(nil), "binlogdata.StreamFilterResponse")
	proto.RegisterType((*StreamKeyRangeRequest)(nil), "binlogdata.StreamKeyRangeRequest")
	proto.RegisterType((*StreamKeyRangeResponse)(nil), "binlogdata.StreamKeyRangeResponse")
	proto.RegisterType((*StreamTablesRequest)(nil), "binlogdata.StreamTablesRequest")
	proto.RegisterType((*StreamTablesResponse)(nil), "binlogdata.StreamTablesResponse")
	proto.RegisterType((*Filter)(nil), "binlogdata.Filter")
	proto.RegisterType((*BinlogSource)(nil), "binlogdata.BinlogSource")
	proto.RegisterEnum("binlogdata.BinlogTransaction_Statement_Category", BinlogTransaction_Statement_Category_name, BinlogTransaction_Statement_Category_value)
}

func init() { proto.RegisterFile("binlogdata.proto", fileDescriptor_binlogdata_ad0a67dfb182b939) }

var fileDescriptor_binlogdata_ad0a67dfb182b939 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0xfd, 0x8c, 0xc1, 0x98, 0x71, 0x7e, 0xcc, 0xe6, 0x47, 0x08, 0xe9, 0x93, 0x10, 0x37, 0xa1,
	0xad, 0x0a, 0x15, 0x55, 0x1f, 0x20, 0x06, 0x37, 0x22, 0x31, 0x24, 0x5a, 0x9c, 0x9b, 0xdc, 0x58,
	0xc6, 0xd9, 0x10, 0x04, 0xf1, 0x12, 0xef, 0x06, 0x95, 0x77, 0xe8, 0x5d, 0x9f, 0xa2, 0x2f, 0xd2,
	0x37, 0xe9, 0x5d, 0x1f, 0xa2, 0xf2, 0x7a, 0x6d, 0x48, 0x2a, 0x35, 0xa4, 0x52, 0xee, 0x66, 0x66,
	0xcf, 0x9c, 0x9d, 0x73, 0x86, 0x35, 0x60, 0x8e, 0x26, 0xe1, 0x8c, 0x8e, 0xaf, 0x7d, 0xee, 0x37,
	0xe7, 0x11, 0xe5, 0x14, 0xc1, 0xaa, 0x52, 0x35, 0xee, 0x1f, 0x48, 0xb4, 0x4c, 0x0e, 0xaa, 0x3b,
	0x9c, 0xce, 0xe9, 0x0a, 0x58, 0xdd, 0x5e, 0xb0, 0xe0, 0x96, 0xdc, 0xc9, 0xb4, 0xde, 0x87, 0x62,
	0xe7, 0xd6, 0x8f, 0x18, 0xe1, 0xe8, 0x10, 0xb4, 0x60, 0x36, 0x21, 0x21, 0xaf, 0x28, 0x35, 0xa5,
	0x51, 0xc0, 0x32, 0x43, 0x08, 0xf2, 0x01, 0x0d, 0xc3, 0x4a, 0x4e, 0x54, 0x45, 0x1c, 0x63, 0x19,
	0x89, 0x16, 0x24, 0xaa, 0xa8, 0x09, 0x36, 0xc9, 0xea, 0x3f, 0x55, 0x28, 0x5b, 0x62, 0x12, 0x37,
	0xf2, 0x43, 0xe6, 0x07, 0x7c, 0x42, 0x43, 0x74, 0x02, 0xc0, 0xb8, 0xcf, 0xc9, 0x1d, 0x09, 0x39,
	0xab, 0x28, 0x35, 0xb5, 0x61, 0xb4, 0x8f, 0x9a, 0x6b, 0x1a, 0xfe, 0x68, 0x69, 0x0e, 0x53, 0x3c,
	0x5e, 0x6b, 0x45, 0x6d, 0x30, 0xc8, 0x82, 0x84, 0xdc, 0xe3, 0x74, 0x4a, 0xc2, 0x4a, 0xbe, 0xa6,
	0x34, 0x8c, 0x76, 0xb9, 0x99, 0xe8, 0xb5, 0xe3, 0x13, 0x37, 0x3e, 0xc0, 0x40, 0xb2, 0xb8, 0xfa,
	0x23, 0x07, 0xa5, 0x8c, 0x0d, 0x39, 0xa0, 0x07, 0x3e, 0x27, 0x63, 0x1a, 0x2d, 0x85, 0xcc, 0x9d,
	0xf6, 0x87, 0x0d, 0x07, 0x69, 0x76, 0x64, 0x1f, 0xce, 0x18, 0xd0, 0x7b, 0x28, 0x06, 0x89, 0x7b,
	0xc2, 0x1d, 0xa3, 0xbd, 0xb7, 0x4e, 0x26, 0x8d, 0xc5, 0x29, 0x06, 0x99, 0xa0, 0xb2, 0xfb, 0x99,
	0xb0, 0x6c, 0x0b, 0xc7, 0x61, 0xfd, 0xbb, 0x02, 0x7a, 0xca, 0x8b, 0xf6, 0x60, 0xd7, 0x72, 0xbc,
	0xcb, 0x01, 0xb6, 0x3b, 0xe7, 0x27, 0x83, 0xde, 0x95, 0xdd, 0x35, 0xff, 0x43, 0x5b, 0xa0, 0x5b,
	0x8e, 0x67, 0xd9, 0x27, 0xbd, 0x81, 0xa9, 0xa0, 0x6d, 0x28, 0x59, 0x8e, 0xd7, 0x39, 0xef, 0xf7,
	0x7b, 0xae, 0x99, 0x43, 0xbb, 0x60, 0x58, 0x8e, 0x87, 0xcf, 0x1d, 0xc7, 0x3a, 0xee, 0x9c, 0x99,
	0x2a, 0x3a, 0x80, 0xb2, 0xe5, 0x78, 0xdd, 0xbe, 0xe3, 0x75, 0xed, 0x0b, 0x6c, 0x77, 0x8e, 0x5d,
	0xbb, 0x6b, 0xe6, 0x11, 0x80, 0x16, 0x97, 0xbb, 0x8e, 0x59, 0x90, 0xf1, 0xd0, 0x76, 0x4d, 0x4d,
	0xd2, 0xf5, 0x06, 0x43, 0x1b, 0xbb, 0x66, 0x51, 0xa6, 0x97, 0x17, 0xdd, 0x63, 0xd7, 0x36, 0x75,
	0x99, 0x76, 0x6d, 0xc7, 0x76, 0x6d, 0xb3, 0x74, 0x9a, 0xd7, 0x73, 0xa6, 0x7a, 0x9a, 0xd7, 0x55,
	0x33, 0x5f, 0xff, 0xaa, 0xc0, 0xde, 0x90, 0x47, 0xc4, 0xbf, 0xfb, 0x3c, 0x99, 0x71, 0x12, 0x61,
	0x72, 0xff, 0x40, 0x18, 0x47, 0x55, 0xd0, 0xe7, 0x94, 0x4d, 0x62, 0xe7, 0x84, 0xbd, 0x25, 0x9c,
	0xe5, 0xe8, 0x2d, 0x68, 0x37, 0x02, 0x2c, 0xbd, 0x42, 0xeb, 0x5e, 0x49, 0x1a, 0x89, 0x58, 0x37,
	0x56, 0x7d, 0xde, 0xd8, 0xfa, 0x35, 0xec, 0x3f, 0x9e, 0x86, 0xcd, 0x69, 0xc8, 0x08, 0x72, 0x00,
	0x25, 0x6d, 0x1e, 0x5f, 0xad, 0x54, 0x0c, 0x66, 0xb4, 0xff, 0xff, 0xeb, 0xde, 0x71, 0x79, 0xf4,
	0xb4, 0x54, 0xff, 0xa6, 0xc0, 0x41, 0x72, 0xcd, 0x19, 0x59, 0x62, 0x3f, 0x1c, 0x93, 0x4d, 0x64,
	0xb7, 0xa0, 0x34, 0x25, 0x4b, 0x2f, 0x8a, 0xf1, 0x99, 0xf2, 0xec, 0x51, 0x66, 0x4c, 0xfa, 0x54,
	0x46, 0x2f, 0xd5, 0x7e, 0x03, 0x87, 0x4f, 0x87, 0x7a, 0x15, 0xf5, 0x5f, 0xd2, 0x8d, 0xbb, 0xfe,
	0x68, 0x46, 0xd8, 0x26, 0xd2, 0x0f, 0x41, 0xe3, 0x02, 0x5c, 0xc9, 0xd5, 0xd4, 0x46, 0x09, 0xcb,
	0xec, 0x9f, 0xb7, 0x9b, 0xde, 0xfc, 0x2a, 0xfa, 0x6e, 0x40, 0x4b, 0x7e, 0x3d, 0xe8, 0x1d, 0x14,
	0xe5, 0x47, 0x52, 0x92, 0x95, 0x9b, 0xe9, 0x47, 0xf3, 0x8c, 0x2c, 0xd9, 0xdc, 0x0f, 0x08, 0x4e,
	0x11, 0x2f, 0x5e, 0x6f, 0xfd, 0x97, 0x02, 0x5b, 0xc9, 0x40, 0x43, 0xfa, 0x10, 0x05, 0x24, 0x76,
	0x70, 0x2a, 0x69, 0x53, 0x07, 0xd3, 0x1c, 0xed, 0x43, 0x81, 0xdd, 0xfa, 0xd1, 0xb5, 0x60, 0x2e,
	0xe1, 0x24, 0x41, 0x9f, 0xc0, 0x10, 0x4e, 0x72, 0x8f, 0x2f, 0xe7, 0x44, 0x78, 0xb8, 0xd3, 0xde,
	0x5f, 0xdd, 0x2a, 0x7c, 0xe2, 0xee, 0x72, 0x4e, 0x30, 0xf0, 0x2c, 0x7e, 0x3c, 0x6a, 0x7e, 0x83,
	0x5f, 0xe2, 0x6a, 0x7f, 0x85, 0x47, 0xfb, 0x5b, 0xbd, 0x64, 0xed, 0xb9, 0x97, 0x6c, 0xbd, 0xb9,
	0x3a, 0x5a, 0x4c, 0x38, 0x61, 0xac, 0x39, 0xa1, 0xad, 0x24, 0x6a, 0x8d, 0x69, 0x6b, 0xc1, 0x5b,
	0xe2, 0x0f, 0xa8, 0xb5, 0xea, 0x1c, 0x69, 0xa2, 0xf2, 0xf1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0xb7, 0x9b, 0x07, 0xde, 0x06, 0x00, 0x00,
}
