topology:
  cells:
    - name: "zone1"
      etcd:
        replicas: 1
      vtctld:
        replicas: 1
      vtgate:
        replicas: 1
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "commerce"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1

vtgate:
  serviceType: LoadBalancer

jobs:
  - name: "create-customer-ks"
    kind: "vtctlclient"
    command: "CreateKeyspace -served_from='master:commerce,replica:commerce,rdonly:commerce' customer"

pmm:
  enabled: false

orchestrator:
  enabled: false
